mybatis:
    basepackage: cn.net.easyinfo.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
logging:
    level:
#        tk.mybatis: DEBUG
        cn.net.easyinfo: DEBUG
        org.springframework.web: debug
    path: D:\chwx\project\chwx-server\log